# Set base image
FROM node:9.3.0-alpine

# Creates an environment variable
ENV ass/app

# Creates the project directory
RUN mkdir $ass

# navigate the working directory to ass
WORKDIR $ass

# Copies the package.json file to the docker's directory
COPY package.json $ass

# Download the dependencies in the copied package.json file
RUN npm install

# Copies all local directory into the docker's directory
COPY . $ass

EXPOSE 3000

# starting command.
CMD npm start